Chat: front module
luweglarz/ft_transcendence pull request #78
Opened 2022-08-03 12:36 UTC by ecogest

Unify all chat components under a dedicated chat module.
Make the whole chat logic independent from the chatbar layout component defined in the home-page module.

2022-08-03 13:37 UTC, S-i-d-V approved these changes
Everything seems to work and to be cleaner. 👍

2022-08-03 14:31 UTC, luweglarz requested changes
I think the directory "services", "class" and "interface" in the frontend sources should be inside the chat module since it contains module utils

2022-08-03 15:20 UTC, ecogest commented
> I think the directory "services", "class" and "interface" in the frontend sources should be inside the chat module since it contains module utils

Absolutely! Just added those changes in c7bc72b

2022-08-04 14:06 UTC, jchemoun approved these changes

2022-08-04 14:07 UTC, merged